### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [davesag/traverse-folders#27]
Hi @davesag , i am a logo designer. I contribute to open source projects that do not have logo. I reviewed the function of the application. And I have designed a logo that represents the function. I explained the logo idea visually.  Please tell me what you think. 

![traversefolders](https://user-images.githubusercontent.com/36298335/56426564-6ee19b00-62c1-11e9-96b3-e7a9578a1ce1.jpg)

readme view;

![tf](https://user-images.githubusercontent.com/36298335/56426225-2c6b8e80-62c0-11e9-81da-be64245fd181.png)

**Comment by davesag** [comment]
Wow that’s really nice. Thanks. Are you happy to make a PR to update the readme? If not I’m happy to do that tomorrow and will run it by you. Cheers Dave

**Comment by davesag** [comment]
I’d probably go for the top one and left align it. I love the colours you’ve chosen.

**Comment by reallinfo** [comment]
Thanks! I sent a pr for all variations. Also, i updated the readme file. Is there any problem? Feel free to contact me if you need help with your other projects.

**Comment by davesag** [comment]
thanks @reallinfo for your contribution. I've added a thank you on the readme

**Comment by davesag** [comment]
also @reallinfo you should add some contact info to your GitHub profile so people can contact you.  If you feel like doing icons for any of my other pinned projects I'd be more than happy to take a look.  Cheers Dave

**Comment by reallinfo** [comment]
Oh, you are right. I added the my gmail adress. Of course I'll review your other projects!
